name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Generate Resources directory
        run: mkdir resources
      - name: Generate Version File
        run: date "+%Y-%m-%dT%H:%M:%SZ" > resources/version.txt
      - name: Copy index.html
        run: cp index.html resources/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './resources'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2