name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Generate Version File
        run: node -p "require('./package.json').version" > resources/version.txt

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './resources'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2